### ISSUE TITLE
Example usage and solver tests are incorrect

### ISSUE THREAD

**Issue by mhluska** [b-inary/postflop-solver#44]
Is the `target_exploitability` arg of the `solve` method supposed to be a percentage like `0.005` (representing 0.5% EV) or is it supposed to be a big blind amount? Like `pot_size * 0.005`?

Reading through the code, it seems like it's supposed to just be a raw percentage like `0.005` but `basic.rs` is suggesting using a big blind amount:

```
let target_exploitability = game.tree_config().starting_pot as f32 * 0.005; // 0.5% of the pot
```

This has huge implications on the runtime of the software and would make it seem much faster than it is for people trying it out via the basic example.

In the tests, [sometimes a percentage is directly used](https://github.com/b-inary/postflop-solver/blob/main/src/game/tests.rs#L783) and other times its a [percentage of the pot](https://github.com/b-inary/postflop-solver/blob/main/src/game/tests.rs#L1181).

**Comment by mhluska** [comment]
Actually, I think I'm wrong and the exploitability arg is supposed to be a big blind amount. I'm not 100% sure but will close unless the author sees something off.

**Comment by b-inary** [comment]
Actually, the `target_exploitability` is assumed to be an absolute amount of chips. So if we want to use a percentage of the starting pot, we have to do the same as in `examples/basic.rs` (so the example is correct).

[This confusing test](https://github.com/b-inary/postflop-solver/blob/ff7a40abb411f3b27589dc6dfd4aa7557c43fcf4/src/game/tests.rs#L783) only does a sanity check, and the parameter is actually a meaningless value (and also this test is not well maintained, because this feature was added by others than me). However, this is definitely confusing, so I will add a comment about it.

**Comment by mhluska** [comment]
Thanks for the reply. This helps a lot.
